// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: product.proto

package product_client

import (
	"context"

	"github.com/xxx-newbee/product/product"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CategoryInfo                = product.CategoryInfo
	CreateCategoryRequest       = product.CreateCategoryRequest
	CreateCategoryResponse      = product.CreateCategoryResponse
	CreateProductRequest        = product.CreateProductRequest
	CreateProductResponse       = product.CreateProductResponse
	CreateSkuRequest            = product.CreateSkuRequest
	CreateSkuResponse           = product.CreateSkuResponse
	DeleteCategoryRequest       = product.DeleteCategoryRequest
	DeleteCategoryResponse      = product.DeleteCategoryResponse
	DeleteProductRequest        = product.DeleteProductRequest
	DeleteProductResponse       = product.DeleteProductResponse
	DeleteSkuRequest            = product.DeleteSkuRequest
	DeleteSkuResponse           = product.DeleteSkuResponse
	GetProductRequest           = product.GetProductRequest
	GetProductResponse          = product.GetProductResponse
	ListCategoryRequest         = product.ListCategoryRequest
	ListCategoryResponse        = product.ListCategoryResponse
	ListProductRequest          = product.ListProductRequest
	ListProductResponse         = product.ListProductResponse
	ListSkuRequest              = product.ListSkuRequest
	ListSkuResponse             = product.ListSkuResponse
	ProductInfo                 = product.ProductInfo
	SkuInfo                     = product.SkuInfo
	UpdateCategoryRequest       = product.UpdateCategoryRequest
	UpdateCategoryResponse      = product.UpdateCategoryResponse
	UpdateProductRequest        = product.UpdateProductRequest
	UpdateProductResponse       = product.UpdateProductResponse
	UpdateProductStatusRequest  = product.UpdateProductStatusRequest
	UpdateProductStatusResponse = product.UpdateProductStatusResponse
	UpdateSkuRequest            = product.UpdateSkuRequest
	UpdateSkuResponse           = product.UpdateSkuResponse

	Product interface {
		CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CreateCategoryResponse, error)
		UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*UpdateCategoryResponse, error)
		DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*DeleteCategoryResponse, error)
		ListCategory(ctx context.Context, in *ListCategoryRequest, opts ...grpc.CallOption) (*ListCategoryResponse, error)
		CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error)
		UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*UpdateProductResponse, error)
		DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*DeleteProductResponse, error)
		GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error)
		ListProduct(ctx context.Context, in *ListProductRequest, opts ...grpc.CallOption) (*ListProductResponse, error)
		UpdateProductStatus(ctx context.Context, in *UpdateProductStatusRequest, opts ...grpc.CallOption) (*UpdateProductStatusResponse, error)
		CreateSku(ctx context.Context, in *CreateSkuRequest, opts ...grpc.CallOption) (*CreateSkuResponse, error)
		UpdateSku(ctx context.Context, in *UpdateSkuRequest, opts ...grpc.CallOption) (*UpdateSkuResponse, error)
		DeleteSku(ctx context.Context, in *DeleteSkuRequest, opts ...grpc.CallOption) (*DeleteSkuResponse, error)
		ListSku(ctx context.Context, in *ListSkuRequest, opts ...grpc.CallOption) (*ListSkuResponse, error)
	}

	defaultProduct struct {
		cli zrpc.Client
	}
)

func NewProduct(cli zrpc.Client) Product {
	return &defaultProduct{
		cli: cli,
	}
}

func (m *defaultProduct) CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CreateCategoryResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.CreateCategory(ctx, in, opts...)
}

func (m *defaultProduct) UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*UpdateCategoryResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.UpdateCategory(ctx, in, opts...)
}

func (m *defaultProduct) DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*DeleteCategoryResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.DeleteCategory(ctx, in, opts...)
}

func (m *defaultProduct) ListCategory(ctx context.Context, in *ListCategoryRequest, opts ...grpc.CallOption) (*ListCategoryResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.ListCategory(ctx, in, opts...)
}

func (m *defaultProduct) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.CreateProduct(ctx, in, opts...)
}

func (m *defaultProduct) UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*UpdateProductResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.UpdateProduct(ctx, in, opts...)
}

func (m *defaultProduct) DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*DeleteProductResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.DeleteProduct(ctx, in, opts...)
}

func (m *defaultProduct) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.GetProduct(ctx, in, opts...)
}

func (m *defaultProduct) ListProduct(ctx context.Context, in *ListProductRequest, opts ...grpc.CallOption) (*ListProductResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.ListProduct(ctx, in, opts...)
}

func (m *defaultProduct) UpdateProductStatus(ctx context.Context, in *UpdateProductStatusRequest, opts ...grpc.CallOption) (*UpdateProductStatusResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.UpdateProductStatus(ctx, in, opts...)
}

func (m *defaultProduct) CreateSku(ctx context.Context, in *CreateSkuRequest, opts ...grpc.CallOption) (*CreateSkuResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.CreateSku(ctx, in, opts...)
}

func (m *defaultProduct) UpdateSku(ctx context.Context, in *UpdateSkuRequest, opts ...grpc.CallOption) (*UpdateSkuResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.UpdateSku(ctx, in, opts...)
}

func (m *defaultProduct) DeleteSku(ctx context.Context, in *DeleteSkuRequest, opts ...grpc.CallOption) (*DeleteSkuResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.DeleteSku(ctx, in, opts...)
}

func (m *defaultProduct) ListSku(ctx context.Context, in *ListSkuRequest, opts ...grpc.CallOption) (*ListSkuResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.ListSku(ctx, in, opts...)
}
