// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: product.proto

package server

import (
	"context"

	"github.com/xxx-newbee/product/internal/logic"
	"github.com/xxx-newbee/product/internal/svc"
	"github.com/xxx-newbee/product/product"
)

type ProductServer struct {
	svcCtx *svc.ServiceContext
	product.UnimplementedProductServer
}

func NewProductServer(svcCtx *svc.ServiceContext) *ProductServer {
	return &ProductServer{
		svcCtx: svcCtx,
	}
}

func (s *ProductServer) CreateCategory(ctx context.Context, in *product.CreateCategoryRequest) (*product.CreateCategoryResponse, error) {
	l := logic.NewCreateCategoryLogic(ctx, s.svcCtx)
	return l.CreateCategory(in)
}

func (s *ProductServer) UpdateCategory(ctx context.Context, in *product.UpdateCategoryRequest) (*product.UpdateCategoryResponse, error) {
	l := logic.NewUpdateCategoryLogic(ctx, s.svcCtx)
	return l.UpdateCategory(in)
}

func (s *ProductServer) DeleteCategory(ctx context.Context, in *product.DeleteCategoryRequest) (*product.DeleteCategoryResponse, error) {
	l := logic.NewDeleteCategoryLogic(ctx, s.svcCtx)
	return l.DeleteCategory(in)
}

func (s *ProductServer) ListCategory(ctx context.Context, in *product.ListCategoryRequest) (*product.ListCategoryResponse, error) {
	l := logic.NewListCategoryLogic(ctx, s.svcCtx)
	return l.ListCategory(in)
}

func (s *ProductServer) CreateProduct(ctx context.Context, in *product.CreateProductRequest) (*product.CreateProductResponse, error) {
	l := logic.NewCreateProductLogic(ctx, s.svcCtx)
	return l.CreateProduct(in)
}

func (s *ProductServer) UpdateProduct(ctx context.Context, in *product.UpdateProductRequest) (*product.UpdateProductResponse, error) {
	l := logic.NewUpdateProductLogic(ctx, s.svcCtx)
	return l.UpdateProduct(in)
}

func (s *ProductServer) DeleteProduct(ctx context.Context, in *product.DeleteProductRequest) (*product.DeleteProductResponse, error) {
	l := logic.NewDeleteProductLogic(ctx, s.svcCtx)
	return l.DeleteProduct(in)
}

func (s *ProductServer) GetProduct(ctx context.Context, in *product.GetProductRequest) (*product.GetProductResponse, error) {
	l := logic.NewGetProductLogic(ctx, s.svcCtx)
	return l.GetProduct(in)
}

func (s *ProductServer) ListProduct(ctx context.Context, in *product.ListProductRequest) (*product.ListProductResponse, error) {
	l := logic.NewListProductLogic(ctx, s.svcCtx)
	return l.ListProduct(in)
}

func (s *ProductServer) UpdateProductStatus(ctx context.Context, in *product.UpdateProductStatusRequest) (*product.UpdateProductStatusResponse, error) {
	l := logic.NewUpdateProductStatusLogic(ctx, s.svcCtx)
	return l.UpdateProductStatus(in)
}

func (s *ProductServer) CreateSku(ctx context.Context, in *product.CreateSkuRequest) (*product.CreateSkuResponse, error) {
	l := logic.NewCreateSkuLogic(ctx, s.svcCtx)
	return l.CreateSku(in)
}

func (s *ProductServer) UpdateSku(ctx context.Context, in *product.UpdateSkuRequest) (*product.UpdateSkuResponse, error) {
	l := logic.NewUpdateSkuLogic(ctx, s.svcCtx)
	return l.UpdateSku(in)
}

func (s *ProductServer) DeleteSku(ctx context.Context, in *product.DeleteSkuRequest) (*product.DeleteSkuResponse, error) {
	l := logic.NewDeleteSkuLogic(ctx, s.svcCtx)
	return l.DeleteSku(in)
}

func (s *ProductServer) ListSku(ctx context.Context, in *product.ListSkuRequest) (*product.ListSkuResponse, error) {
	l := logic.NewListSkuLogic(ctx, s.svcCtx)
	return l.ListSku(in)
}
